name: Build

on:
  push:
  pull_request:

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Need full history for git versioning

      - uses: actions/setup-dotnet@v5

      - name: Build
        run: dotnet build
