name: Release

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Need full history for git versioning

      - uses: actions/setup-dotnet@v5

      - name: Build win-x64
        run: dotnet publish "SteamPresenceSync/SteamPresenceSync.csproj" -o "publish/win-x64" -c Release -r win-x64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:SelfContained=true

      - name: Build win-arm64
        run: dotnet publish "SteamPresenceSync/SteamPresenceSync.csproj" -o "publish/win-arm64" -c Release -r win-arm64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:SelfContained=true
      
      - name: Rename executables
        shell: pwsh
        run: |
          Move-Item -Path publish/win-x64/SteamPresenceSync.exe -Destination publish/win-x64/SteamPresenceSync-x64.exe -ErrorAction Stop
          Move-Item -Path publish/win-arm64/SteamPresenceSync.exe -Destination publish/win-arm64/SteamPresenceSync-arm64.exe -ErrorAction Stop

      - uses: dotnet/nbgv@v0.4.2
        id: nbgv

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{ steps.nbgv.outputs.SimpleVersion }}"
          artifacts: "publish/win-x64/*.exe,publish/win-arm64/*.exe"
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true
          artifactErrorsFailBuild: true
          makeLatest: true
          generateReleaseNotes: true
          prerelease: ${{ !steps.nbgv.outputs.PublicRelease }}
